### ISSUE TITLE
Support multiple routes for the same action

### ISSUE THREAD

**Issue by abatishchev** [pmhsfelix/drum#11]
Currently for a configuration like this:
```
[Route("api/product/{searchCriteria}]
[Route("api/product/type/id/{guid}"]
public async Task<IHttpActionResult> GetProduct()
{
}
```
you will receive the exception:

    Multiple routes for the same action. Action: <action>, previous route <route1>, new route: <route2>

Is it possible to actually support multiple routes?

In case of more than 1 route is found use say `DefaultAmbiguousRouteResolver` which returns `routes.First()`, or an implementation of `IAmbiguousRouteResolver` passed to `MapHttpAttributeRoutesAndUseUriMaker()` if any.

Other way to support such scenario is to respect the RouteAttribute.Name property, they should be different when applied to the same action.

**Comment by pmhsfelix** [comment]
I've added some experimental support for multiple routes per action. Check the example at: https://github.com/pmhsfelix/drum/blob/master/src/Drum.Tests/MultipleRouteTests.cs

**Comment by abatishchev** [comment]
Looks like exactly what I was looking for. Thanks!
