### ISSUE TITLE
Array parameters

### ISSUE THREAD

**Issue by svickers** [pmhsfelix/drum#13]
When an action has an IEnumerable parameter the code to handle complex objects is iterating over the properties instead of the items within the array.
Simple test:

        [Route("")]
        public void GetByIds(int[] id) { }

        [Fact]
        public void Can_make_uri_for_action_with_array()
        {
            var uri = _uriMaker.UriFor(c => c.GetByIds(new []{ 1, 2, 3 }));
            Assert.Equal("http://example.org/api/UriMakerTests/resources?id=1&id=2&id=3",uri.ToString());
        }

Actual:   http://example.org/api/UriMakerTests/resources?Length=3&LongLength=3&Rank=1&SyncRoot=System.Int32[]&IsReadOnly=False&IsFixedSize=True&IsSynchronized=False

Also would be helpful if it worked for an object parameter that has list properties like:

    public class PageInfo
    {
        public int page { get; set; }
        public int count { get; set; }
        public List<int> someList { get; set; }
    }

I took a crack at a fix but hit a wall building the RouteValueHandler.  Thanks for the work on this, link generation in web api is really weak without drum.

**Comment by pmhsfelix** [comment]
Hi,

Thanks for the feedback. I need to further analyse your requirement, but it seems to make sense.
I'll provide feedback soon.

Thanks
Pedro

**Comment by pmhsfelix** [comment]
Should be available on 0.5.0. Please check tests.
