### ISSUE TITLE
How about adding overload HttpConfigration.MapHttpAttributeRoutesAndUseUriMaker with "IInlineConstraintResolver" 

### ISSUE THREAD

**Issue by hid-shibayama** [pmhsfelix/drum#15]
I'm sorry my English is bad.
First of all, please let me to thank you for your work. 
I use UrlMaker conveniently.

Let’s get down to business.

How about adding "HttpConfigration.MapHttpAttributeRoutesAndUseUriMaker" overload method with "IInlineConstraintResolver"?
I want to use both UrlMaker and custom IRouteConstraint.

Kind Regards.

**Comment by pmhsfelix** [comment]
Added on 0.4.0.

**Comment by hid-shibayama** [comment]
Version 0.4.0 works well.
Thank you!!
